services:
  eridon_bot:
    container_name: eridon_bot
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file:
      - bot/.env
    networks:
      - web_network
    restart: unless-stopped

networks:
  web_network:
    external: true
    name: web_network
